# Generated by Django 5.0.7 on 2024-08-27 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypublicitaire',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companypublicitaire',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companypublicitaire',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companypublicitaire',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companypublicitaire',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companypublicitaire',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
