# Generated by Django 4.2 on 2024-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_lead_campaign'),
        ('campaigns', '0002_remove_companypublicitaire_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypublicitaire',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='lead.lead'),
        ),
    ]
