# Generated by Django 4.2 on 2024-09-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0009_history_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Rendez.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'Utilisateur')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
