# Generated by Django 4.2 on 2024-09-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0009_history_user'),
        ('notification', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Rendez.event'),
        ),
    ]
