# Generated by Django 4.2 on 2024-09-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0009_history_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Rendez.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
