# Generated by Django 4.2 on 2024-09-05 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0009_history_user'),
        ('notification', '0011_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Rendez.event'),
        ),
    ]
