# Generated by Django 5.0.7 on 2024-08-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('heure', models.TimeField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=15)),
            ],
        ),
    ]
