# Generated by Django 5.0.7 on 2024-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filters',
            field=models.JSONField(default=dict),
        ),
    ]
