# Generated by Django 5.0.7 on 2024-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Contacte', 'Contacte'), ('Qualifie', 'Qualifie'), ('Converti', 'Converti'), ('Perdu', 'Perdu')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
