# Generated by Django 5.0.7 on 2024-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Contacte', 'Contacte'), ('Qualifie', 'Qualifie'), ('Converti', 'Converti'), ('Perdu', 'Perdu')], default='Nouveau', max_length=50),
        ),
    ]
