# Generated by Django 5.0.7 on 2024-08-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
