# Generated by Django 5.0.7 on 2024-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_leadhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
