# Generated by Django 5.0.7 on 2024-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_alter_leadhistory_options_alter_leadhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10),
        ),
    ]
