# Generated by Django 4.2 on 2024-09-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_leadhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
