# Generated by Django 4.2 on 2024-09-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_lead_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
