# Generated by Django 4.2 on 2024-09-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_companypublicitaire_address_and_more'),
        ('lead', '0014_lead_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_campaigns', to='campaigns.companypublicitaire'),
        ),
    ]
