# Generated by Django 4.2 on 2024-09-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_alter_interaction_type_interaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='note',
            new_name='content',
        ),
    ]
