# Generated by Django 5.0.7 on 2024-08-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
