# Generated by Django 5.0.7 on 2024-08-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
