# Generated by Django 5.0.7 on 2024-08-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_note_lead_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
