# Generated by Django 5.0.7 on 2024-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
