# Generated by Django 5.0.7 on 2024-08-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='event',
        ),
        migrations.AddField(
            model_name='history',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
