# Generated by Django 5.0.7 on 2024-08-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0005_remove_history_event_history_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='event_id',
        ),
        migrations.AddField(
            model_name='history',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
