# Generated by Django 5.0.7 on 2024-08-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0006_remove_history_event_id_history_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
