# Generated by Django 5.0.7 on 2024-08-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0007_alter_history_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
