# Generated by Django 4.2 on 2024-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0009_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
