# Generated by Django 4.2 on 2024-09-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0013_alter_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
