# Generated by Django 4.2 on 2024-09-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rendez', '0015_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rendez.event'),
        ),
    ]
